
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

contract multiplicationContract {
    uint32 public timestamp;
    uint public value = 1;

    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);

        tvm.accept();

        timestamp = now;
    }

    modifier checkPubkeyAndAccept {
		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
		_;
	}

    function isNumber(uint number) public view returns(bool) {
            if (number > 0 && number < 11) 
                return true;

            return false;
    }

    function multiply(uint a) public checkPubkeyAndAccept {
        require(isNumber(a), 101, 'Введенное число не принадлежит заданному диапазону!');
		value *= a; 
	}
}
