
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

contract multiplicationContract {
    uint32 public timestamp;
    string[] public names;

    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);

        tvm.accept();

        timestamp = now;
    }

    modifier checkPubkeyAndAccept {
		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
		_;
	}

    function getQueue(string name) public checkPubkeyAndAccept {
        names.push(name);
    }

    function callNext() public checkPubkeyAndAccept {
        require(!names.empty(), 101, 'Очередь пуста!');

       for (uint256 i = 0; i < names.length - 1; i++) {
           names[i] = names[i + 1];
       }

        names.pop();
    }
}
